apiVersion: v1
kind: ConfigMap
metadata:
  name: services-config
  namespace: predictive-maintenance
data:
  ingestion-iiot-url: "http://ingestion-iiot-service:8081"
  preprocessing-url: "http://preprocessing-service:8082"
  extraction-features-url: "http://extraction-features-service:8083"
  detection-anomalies-url: "http://detection-anomalies-service:8084"
  prediction-rul-url: "http://prediction-rul-service:8085"
  orchestrateur-maintenance-url: "http://orchestrateur-maintenance-service:8087"
  dashboard-monitoring-url: "http://dashboard-monitoring-service:8086"
  mlflow-url: "http://mlflow-service:5000"

