apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: predictive-maintenance-ingress
  namespace: predictive-maintenance
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: api.predictive-maintenance.local
    http:
      paths:
      - path: /api/v1/ingestion
        pathType: Prefix
        backend:
          service:
            name: ingestion-iiot-service
            port:
              number: 8081
      - path: /api/v1/preprocessing
        pathType: Prefix
        backend:
          service:
            name: preprocessing-service
            port:
              number: 8082
      - path: /api/v1/extraction
        pathType: Prefix
        backend:
          service:
            name: extraction-features-service
            port:
              number: 8083
      - path: /api/v1/anomalies
        pathType: Prefix
        backend:
          service:
            name: detection-anomalies-service
            port:
              number: 8084
      - path: /api/v1/rul
        pathType: Prefix
        backend:
          service:
            name: prediction-rul-service
            port:
              number: 8085
      - path: /api/v1/interventions
        pathType: Prefix
        backend:
          service:
            name: orchestrateur-maintenance-service
            port:
              number: 8087
  - host: dashboard.predictive-maintenance.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dashboard-monitoring-service
            port:
              number: 8086

